export const CONTRACT_ID =
  "CD5JIH7M766UASULUTW2373QJ75V54RXPYYZRL2AKSRC5K2SQGP3XVVM";

// 🔹 Direcciones de los tokens (testnet wrappers)
// XLM usa un contrato wrapper en Soroban, no puede ser "native"
export const TOKEN_ADDRESSES = {
  XLM: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC", // XLM wrapper en testnet
  USDC: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA", // USDC en testnet
} as const;

export const POOL_CONTRACT_ID =
  "CB7XWRL5YR7A5WEUVGEWUWT46O2ESYNWM2QIQR5AYN7PDYO47R743NVY";
